import { messageMapKey, type MessageMapKeyInput } from '@/store/chat/utils/messageMapKey';

export interface ServerCtxKeyInput extends MessageMapKeyInput {
  userId: string;
}

/**
 * Build the server-side context key for the message queue.
 *
 * Format: `{userId}:{messageMapKey(input)}`
 *
 * The inner segment is generated by the same `messageMapKey` used on the
 * frontend so that both sides produce identical keys for the same
 * conversation context; the `{userId}:` prefix adds multi-tenant isolation.
 */
export const buildServerCtxKey = ({ userId, ...input }: ServerCtxKeyInput): string => {
  if (!userId) throw new Error('buildServerCtxKey: userId is required');
  return `${userId}:${messageMapKey(input)}`;
};

/**
 * Build the ctxKey used to serialise bot messages.
 *
 * Bot threads on chat platforms map 1:1 to a LobeChat topic, but the topic
 * id is only known after the first agent run completes — so we key by the
 * platform thread id instead, which is stable across the entire lifetime of
 * the Chat SDK thread.
 */
export const buildBotCtxKey = (
  userId: string,
  platform: string,
  platformThreadId: string,
): string => {
  if (!userId) throw new Error('buildBotCtxKey: userId is required');
  return `${userId}:bot:${platform}:${platformThreadId}`;
};

export interface MessageQueueRedisKeys {
  active: string;
  dedup: string;
  lock: string;
  queue: string;
}

/**
 * Map a ctxKey to the four Redis keys used by the message queue service.
 * Centralised so callers never hand-assemble key names.
 */
export const buildMessageQueueRedisKeys = (ctxKey: string): MessageQueueRedisKeys => ({
  active: `queue:active:${ctxKey}`,
  dedup: `queue:dedup:${ctxKey}`,
  lock: `queue:lock:${ctxKey}`,
  queue: `queue:msg:${ctxKey}`,
});
